import { readFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import { openPool } from '../db/pool.js';
import {
  persistRun,
  getDailyMetrics,
  getRuleCounts,
  getFindings,
  getRun,
} from '../db/repositories.js';
import { executeRun } from './orchestrator.js';
import { renderRunReport } from '../report/render.js';
import { EsClient } from '../es/client.js';
import { FakeLlmClient } from '../llm/client-fake.js';
import { buildBatches } from '../llm/grouping.js';
import { loadConfig } from '../config/env.js';

/**
 * Acceptance verification (design section 7.5, acceptance-data contract).
 *
 * Runs the acceptance teams against the mock and compares the PERSISTED SQL rows and the
 * rendered CSV exports against `test/fixtures/expected-results.json`.
 *
 * The manifest is hand-authored from the fixture definitions and is never generated by
 * this pipeline: an oracle produced by the code under test would agree with any bug that
 * happened to be self-consistent.
 */

export const MANIFEST_PATH = path.join('test', 'fixtures', 'expected-results.json');

/**
 * @typedef {object} Failure
 * @property {string} where
 * @property {unknown} expected
 * @property {unknown} actual
 */

class Checker {
  constructor() {
    /** @type {Failure[]} */
    this.failures = [];
    this.checks = 0;
  }

  /**
   * Numeric comparison uses the tolerance of the STORED precision, not of the
   * hand-computed value: derived rates are persisted as DECIMAL(18,6), so a daily
   * alerts_per_hour of 1/24 reads back as 0.041667. The manifest records the exact
   * arithmetic and the comparison allows the rounding that storage introduces - anything
   * larger than half a unit in the last stored place is a real disagreement.
   *
   * @param {string} where
   * @param {unknown} expected
   * @param {unknown} actual
   */
  equal(where, expected, actual) {
    this.checks += 1;
    const same =
      expected === null || actual === null
        ? expected === actual
        : typeof expected === 'number'
          ? Math.abs(Number(actual) - expected) <= 5e-7
          : String(expected) === String(actual);
    if (!same) this.failures.push({ where, expected, actual });
  }

  /**
   * @param {string} where
   * @param {unknown[]} expected
   * @param {unknown[]} actual
   */
  deepEqual(where, expected, actual) {
    this.checks += 1;
    if (JSON.stringify(expected) !== JSON.stringify(actual)) {
      this.failures.push({ where, expected, actual });
    }
  }
}

/**
 * @param {any[]} rows
 * @param {string} schema
 * @returns {any[]}
 */
const ofSchema = (rows, schema) => rows.filter((r) => r.alert_schema === schema);

/**
 * @param {unknown} value
 * @returns {string}
 */
function dateKey(value) {
  if (value instanceof Date) return value.toISOString().slice(0, 10);
  return String(value).slice(0, 10);
}

/**
 * @param {any[]} daily
 * @returns {Record<string, number>}
 */
function sumDaily(daily) {
  /** @type {Record<string, number>} */
  const totals = {
    alerts: 0,
    distinct_sum: 0,
    flagged_by_rule: 0,
    flagged_by_rule_distinct_sum: 0,
    flagged_by_llm: 0,
    flagged_by_llm_distinct_sum: 0,
    needs_review_sum: 0,
    assessed_good_sum: 0,
    unassessed_sum: 0,
    phase2_gaps_sum: 0,
    suppressed: 0,
    suppression_unmeasured: 0,
    node_name_numerator: 0,
    node_name_denominator: 0,
    key_inflation_numerator: 0,
    key_inflation_denominator: 0,
  };
  for (const d of daily) {
    totals.alerts += d.alerts;
    totals.distinct_sum += d.distinct_alerts;
    totals.flagged_by_rule += d.flagged_by_rule;
    totals.flagged_by_rule_distinct_sum += d.flagged_by_rule_distinct;
    totals.flagged_by_llm += d.flagged_by_llm;
    totals.flagged_by_llm_distinct_sum += d.flagged_by_llm_distinct;
    totals.needs_review_sum += d.needs_review;
    totals.assessed_good_sum += d.assessed_good;
    totals.unassessed_sum += d.unassessed;
    totals.phase2_gaps_sum += d.phase2_gaps;
    totals.suppressed += d.suppressed;
    totals.suppression_unmeasured += d.suppression_unmeasured;
    totals.node_name_numerator += d.node_name_numerator;
    totals.node_name_denominator += d.node_name_denominator;
    totals.key_inflation_numerator += d.key_inflation_numerator;
    totals.key_inflation_denominator += d.key_inflation_denominator;
  }
  return totals;
}

/**
 * Verify one team against its manifest entry.
 *
 * @param {Checker} check
 * @param {string} teamId
 * @param {any} expected
 * @param {object} actual
 * @returns {void}
 */
function verifyTeam(check, teamId, expected, actual) {
  const { run, daily, ruleCounts, findings, batches } = actual;

  check.equal(`${teamId}.phase_derived`, expected.phase_derived, run.phase_derived);
  check.equal(
    `${teamId}.phase2_readiness_pct`,
    expected.phase2_readiness_pct,
    run.phase2_readiness_pct === null ? null : Number(run.phase2_readiness_pct),
  );

  // Identity states are mutually exclusive, so the counts must partition the work list.
  /** @type {Record<string, number>} */
  const states = {};
  for (const f of findings) states[f.quality_state] = (states[f.quality_state] ?? 0) + 1;
  for (const [state, count] of Object.entries(expected.identity_states ?? {})) {
    check.equal(`${teamId}.identity_states.${state}`, count, states[state] ?? 0);
  }
  check.equal(
    `${teamId}.identity_states.total`,
    Object.values(expected.identity_states ?? {}).reduce((a, b) => a + Number(b), 0),
    findings.length,
  );

  for (const [schema, expectedSchema] of Object.entries(expected.schemas ?? {})) {
    const schemaDaily = ofSchema(daily, schema);
    const es = /** @type {any} */ (expectedSchema);

    check.equal(
      `${teamId}.${schema}.identities`,
      es.identities,
      findings.filter((f) => f.alert_schema === schema).length,
    );

    const totals = sumDaily(schemaDaily);
    for (const [field, value] of Object.entries(es.totals ?? {})) {
      if (field === 'distinct_per_day') {
        check.equal(`${teamId}.${schema}.totals.distinct_per_day`, value, totals.distinct_sum / 7);
      } else if (field === 'alerts_per_hour') {
        check.equal(`${teamId}.${schema}.totals.alerts_per_hour`, value, totals.alerts / 168);
      } else if (field === 'node_name_ratio') {
        check.equal(
          `${teamId}.${schema}.totals.node_name_ratio`,
          value,
          totals.node_name_denominator === 0
            ? null
            : totals.node_name_numerator / totals.node_name_denominator,
        );
      } else if (field === 'key_inflation_ratio') {
        check.equal(
          `${teamId}.${schema}.totals.key_inflation_ratio`,
          value,
          totals.key_inflation_denominator === 0
            ? null
            : totals.key_inflation_numerator / totals.key_inflation_denominator,
        );
      } else {
        check.equal(`${teamId}.${schema}.totals.${field}`, value, totals[field]);
      }
    }

    // Buckets the manifest does not mention must exist and be entirely zero: a missing
    // day would otherwise pass unnoticed.
    const byDate = new Map(schemaDaily.map((d) => [dateKey(d.snapshot_date), d]));
    for (const [date, expectedDay] of Object.entries(es.daily ?? {})) {
      const actualDay = byDate.get(date);
      if (!actualDay) {
        check.failures.push({
          where: `${teamId}.${schema}.daily.${date}`,
          expected: 'present',
          actual: 'missing',
        });
        continue;
      }
      for (const [field, value] of Object.entries(/** @type {any} */ (expectedDay))) {
        check.equal(`${teamId}.${schema}.daily.${date}.${field}`, value, Number(actualDay[field]));
      }
    }
    for (const [date, day] of byDate) {
      if (date in (es.daily ?? {})) continue;
      check.equal(
        `${teamId}.${schema}.daily.${date}.alerts (unlisted must be zero)`,
        0,
        day.alerts,
      );
      check.equal(
        `${teamId}.${schema}.daily.${date}.flagged_by_rule (unlisted must be zero)`,
        0,
        day.flagged_by_rule,
      );
    }

    // Per-rule counts, including that no unexpected rule fired.
    const schemaRules = ofSchema(ruleCounts, schema);
    /** @type {Map<string, Map<string, [number, number]>>} */
    const actualRules = new Map();
    for (const r of schemaRules) {
      const date = dateKey(r.snapshot_date);
      if (!actualRules.has(date)) actualRules.set(date, new Map());
      /** @type {Map<string, [number, number]>} */ (actualRules.get(date)).set(r.rule_id, [
        r.match_count,
        r.distinct_count,
      ]);
    }
    for (const [date, rules] of Object.entries(es.rule_counts ?? {})) {
      for (const [ruleId, pair] of Object.entries(/** @type {any} */ (rules))) {
        check.deepEqual(
          `${teamId}.${schema}.rule_counts.${date}.${ruleId}`,
          pair,
          actualRules.get(date)?.get(ruleId) ?? null,
        );
      }
    }
    const expectedRuleKeys = new Set(
      Object.entries(es.rule_counts ?? {}).flatMap(([date, rules]) =>
        Object.keys(/** @type {any} */ (rules)).map((ruleId) => `${date}|${ruleId}`),
      ),
    );
    for (const r of schemaRules) {
      const key = `${dateKey(r.snapshot_date)}|${r.rule_id}`;
      if (!expectedRuleKeys.has(key)) {
        check.failures.push({
          where: `${teamId}.${schema}.rule_counts.${key}`,
          expected: 'no finding',
          actual: [r.match_count, r.distinct_count],
        });
      }
    }
  }

  if (expected.suppression) {
    const suppressedRows = daily.reduce((sum, d) => sum + d.suppressed, 0);
    const unmeasured = daily.reduce((sum, d) => sum + d.suppression_unmeasured, 0);
    check.equal(
      `${teamId}.suppression.suppressed_rows`,
      expected.suppression.suppressed_rows,
      suppressedRows,
    );
    check.equal(
      `${teamId}.suppression.unmeasured_leaves`,
      expected.suppression.unmeasured_leaves,
      unmeasured,
    );
    if (expected.suppression.suppressed_node_names) {
      const actualNames = findings
        .filter((f) => f.core_rule_ids.split(',').includes('R5'))
        .map((f) => f.node_name)
        .sort();
      check.deepEqual(
        `${teamId}.suppression.suppressed_node_names`,
        [...expected.suppression.suppressed_node_names].sort(),
        actualNames,
      );
    }
    if (expected.suppression.not_suppressed_node_names) {
      const suppressedNames = new Set(
        findings.filter((f) => f.core_rule_ids.split(',').includes('R5')).map((f) => f.node_name),
      );
      for (const name of expected.suppression.not_suppressed_node_names) {
        check.equal(
          `${teamId}.suppression.not_suppressed.${name}`,
          false,
          suppressedNames.has(name),
        );
      }
    }
  }

  if (expected.llm_batches) {
    check.equal(`${teamId}.llm_batches.total`, expected.llm_batches.total, batches.length);
    /** @type {Record<string, number[]>} */
    const sizesByGroup = {};
    for (const batch of batches) {
      (sizesByGroup[batch.groupValue] ??= []).push(batch.alerts.length);
    }
    for (const [group, sizes] of Object.entries(expected.llm_batches.partition_sizes_by_group)) {
      check.deepEqual(`${teamId}.llm_batches.${group}`, sizes, sizesByGroup[group] ?? null);
    }
  }
}

/**
 * Cross-check the rendered CSV against the persisted rows it was rendered from.
 *
 * @param {Checker} check
 * @param {string} teamId
 * @param {string} outDir
 * @param {any[]} daily
 * @param {any[]} findings
 * @returns {void}
 */
function verifyCsv(check, teamId, outDir, daily, findings) {
  for (const name of ['daily_metrics.csv', 'rule_counts.csv', 'alert_worklist.csv']) {
    const file = path.join(outDir, name);
    check.equal(`${teamId}.csv.${name} exists`, true, existsSync(file));
  }

  const dailyCsv = readFileSync(path.join(outDir, 'daily_metrics.csv'), 'utf8')
    .trim()
    .split('\r\n');
  check.equal(`${teamId}.csv.daily_metrics rows`, daily.length, dailyCsv.length - 1);

  const headers = dailyCsv[0].split(',');
  const alertsIndex = headers.indexOf('alerts');
  const csvAlerts = dailyCsv
    .slice(1)
    .reduce((sum, line) => sum + Number(line.split(',')[alertsIndex]), 0);
  check.equal(
    `${teamId}.csv.daily_metrics alerts total`,
    daily.reduce((sum, d) => sum + d.alerts, 0),
    csvAlerts,
  );

  const worklistCsv = readFileSync(path.join(outDir, 'alert_worklist.csv'), 'utf8').trim();
  // One row per identity, never divided by seven.
  const worklistRows = worklistCsv.split('\r\n').length - 1;
  check.equal(`${teamId}.csv.alert_worklist rows`, findings.length, worklistRows);
}

/**
 * Run acceptance verification.
 *
 * @param {object} [options]
 * @param {string} [options.manifestPath]
 * @param {string} [options.outDir]
 * @param {string} [options.database]
 * @returns {Promise<{ok: boolean, checks: number, failures: Failure[]}>}
 */
export async function verifyAcceptance(options = {}) {
  const config = loadConfig();
  const manifest = JSON.parse(readFileSync(options.manifestPath ?? MANIFEST_PATH, 'utf8'));
  const runAt = new Date(manifest.run_at);
  const esClient = new EsClient(config.es);
  const check = new Checker();

  const pool = await openPool(config.sql, options.database ?? config.sql.database);
  try {
    for (const [teamId, expected] of Object.entries(manifest.teams)) {
      const client = new FakeLlmClient();
      const { payload, summary } = await executeRun({
        teamId,
        runAt,
        config,
        esClient,
        llmClient: client,
        // No pool: acceptance always classifies fresh, so a verdict stored by an earlier
        // verification run cannot mask a regression in the assessment path.
        pool: null,
      });
      await persistRun(pool, payload);

      const outDir = path.join(options.outDir ?? path.join('out', 'acceptance'), teamId);
      await renderRunReport(pool, summary.runId, outDir);

      const [run, daily, ruleCounts, findings] = await Promise.all([
        getRun(pool, summary.runId),
        getDailyMetrics(pool, summary.runId),
        getRuleCounts(pool, summary.runId),
        getFindings(pool, summary.runId),
      ]);

      // Batches are recomputed from the same eligible set so partition shapes can be
      // asserted independently of whether the model was called.
      // Batch shapes are recomputed from the persisted eligible set so partition sizes
      // can be asserted independently of whether the model was actually called.
      const eligible = payload.findings.filter((f) => f.quality_state !== 'rule_flagged');
      const batches = buildBatches(
        /** @type {any[]} */ (
          eligible.map((f) => ({
            application: f.application,
            keyField: f.key_field,
            schema: f.alert_schema,
            alertRuleUrl: f.alert_rule_url,
          }))
        ),
        {
          runId: summary.runId,
          promptVersion: run.prompt_version,
          modelVersion: run.model_version ?? 'fake-model-1',
        },
      );

      verifyTeam(check, teamId, expected, { run, daily, ruleCounts, findings, batches });
      verifyCsv(check, teamId, outDir, daily, findings);

      // The window contract is identical for every team.
      const v1Daily = ofSchema(daily, 'v1');
      check.equal(`${teamId}.window.bucket_count`, manifest.window.bucket_count, v1Daily.length);
      check.equal(
        `${teamId}.window.covered_hours_total`,
        manifest.window.covered_hours_total,
        v1Daily.reduce((sum, d) => sum + Number(d.covered_hours), 0),
      );
    }
  } finally {
    await pool.close();
  }

  return { ok: check.failures.length === 0, checks: check.checks, failures: check.failures };
}
